blank_issues_enabled: false
contact_links:
  - name: Feature requests, ideas, and general support
    url: https://github.com/likeandscribe/frontpage/discussions
    about: "We use discussions for things that aren't bugs."
