[package]
name = "drainpipe"
version = "0.2.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
tokio = { version = "1.38.0", features = ["full"] }
tokio-metrics = "0.3.1"
tokio-tungstenite = { version = "0.23.0", features = ["native-tls"] }
