name: label
on: pull_request_target

jobs:
  labeller:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/labeler@v5
      with:
        sync-labels: true
